# Dependencies
rouge:      pygments

# Permalinks
permalink:        /:title/

# Setup
title:            Junhong Xu
tagline:          'Junhong Xu'
description:      'A Ph.D. student in Indiana University focusing on reinforcement learning and control for mobile vehicles.'
avatar: https://avatars.githubusercontent.com/junhongxu
baseurl:          "/JunhongXu.github.io"
email:      xu14@iu.edu

author:
  name:           'Junhong Xu'

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/JunhongXu

gems: [jekyll-paginate]
